#!/usr/bin/env bash
set -eo pipefail

current_file=~/.pomodoro/current
icon_file=~/.pomo/icon.png

# extract current pomo
pomo=$(cat $current_file)

# extract duration mins
duration=$(echo $pomo | cut -f2 -d'=')

sleep ${duration}m

# check if the current file contents have changed
# if yes, then exit since current pomo was canceled or new pomo was started
pomo_now=$(cat $current_file)

if [[ $pomo = $pomo_now ]]; then
	notify-send --icon=$icon_file "Pomodoro ended." "Stand up. Hydrate. Stretch. Blink. Look outside.\nThen resume."
fi
